# Generated by Django 5.2.14 on 2026-06-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_transaction_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
    ]
